from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_EzShareCPAP(object):
    def setupUi(self, EzShareCPAP):
        EzShareCPAP.setObjectName("EzShareCPAP")
        EzShareCPAP.resize(634, 387)
        self.centralwidget = QtWidgets.QWidget(parent=EzShareCPAP)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setObjectName("pathLayout")
        self.pathLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pathLabel.setFont(font)
        self.pathLabel.setObjectName("pathLabel")
        self.pathLayout.addWidget(self.pathLabel)
        self.pathEntry = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathEntry.sizePolicy().hasHeightForWidth())
        self.pathEntry.setSizePolicy(sizePolicy)
        self.pathEntry.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.pathEntry.setFont(font)
        self.pathEntry.setReadOnly(True)
        self.pathEntry.setObjectName("pathEntry")
        self.pathLayout.addWidget(self.pathEntry)
        self.pathBrowseBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathBrowseBtn.sizePolicy().hasHeightForWidth())
        self.pathBrowseBtn.setSizePolicy(sizePolicy)
        self.pathBrowseBtn.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.pathBrowseBtn.setFont(font)
        self.pathBrowseBtn.setObjectName("pathBrowseBtn")
        self.pathLayout.addWidget(self.pathBrowseBtn)
        self.verticalLayout.addLayout(self.pathLayout)
        
        self.urlLayout = QtWidgets.QHBoxLayout()
        self.urlLayout.setObjectName("urlLayout")
        self.urlLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.urlLabel.setFont(font)
        self.urlLabel.setObjectName("urlLabel")
        self.urlLayout.addWidget(self.urlLabel)
        self.urlEntry = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlEntry.sizePolicy().hasHeightForWidth())
        self.urlEntry.setSizePolicy(sizePolicy)
        self.urlEntry.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.urlEntry.setFont(font)
        self.urlEntry.setObjectName("urlEntry")
        self.urlLayout.addWidget(self.urlEntry)
        self.verticalLayout.addLayout(self.urlLayout)
        
        self.ssidLayout = QtWidgets.QHBoxLayout()
        self.ssidLayout.setObjectName("ssidLayout")
        self.ssidLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ssidLabel.setFont(font)
        self.ssidLabel.setObjectName("ssidLabel")
        self.ssidLayout.addWidget(self.ssidLabel)
        self.ssidEntry = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssidEntry.sizePolicy().hasHeightForWidth())
        self.ssidEntry.setSizePolicy(sizePolicy)
        self.ssidEntry.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.ssidEntry.setFont(font)
        self.ssidEntry.setObjectName("ssidEntry")
        self.ssidLayout.addWidget(self.ssidEntry)
        self.verticalLayout.addLayout(self.ssidLayout)
        
        self.pskLayout = QtWidgets.QHBoxLayout()
        self.pskLayout.setObjectName("pskLayout")
        self.pskLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pskLabel.setFont(font)
        self.pskLabel.setObjectName("pskLabel")
        self.pskLayout.addWidget(self.pskLabel)
        self.pskEntry = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pskEntry.sizePolicy().hasHeightForWidth())
        self.pskEntry.setSizePolicy(sizePolicy)
        self.pskEntry.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.pskEntry.setFont(font)
        self.pskEntry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pskEntry.setObjectName("pskEntry")
        self.pskLayout.addWidget(self.pskEntry)
        self.verticalLayout.addLayout(self.pskLayout)
        
        self.importOscarCheckbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importOscarCheckbox.sizePolicy().hasHeightForWidth())
        self.importOscarCheckbox.setSizePolicy(sizePolicy)
        self.importOscarCheckbox.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.importOscarCheckbox.setFont(font)
        self.importOscarCheckbox.setObjectName("importOscarCheckbox")
        self.verticalLayout.addWidget(self.importOscarCheckbox)
        
        self.quitCheckbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitCheckbox.sizePolicy().hasHeightForWidth())
        self.quitCheckbox.setSizePolicy(sizePolicy)
        self.quitCheckbox.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.quitCheckbox.setFont(font)
        self.quitCheckbox.setObjectName("quitCheckbox")
        self.verticalLayout.addWidget(self.quitCheckbox)
        
        self.btnLayout = QtWidgets.QHBoxLayout()
        self.btnLayout.setObjectName("btnLayout")
        self.startBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startBtn.sizePolicy().hasHeightForWidth())
        self.startBtn.setSizePolicy(sizePolicy)
        self.startBtn.setMinimumHeight(40)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet("background-color: rgb(51, 153, 102); color: white;")
        self.startBtn.setObjectName("startBtn")
        self.btnLayout.addWidget(self.startBtn)
        
        self.saveBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBtn.sizePolicy().hasHeightForWidth())
        self.saveBtn.setSizePolicy(sizePolicy)
        self.saveBtn.setMinimumHeight(40)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("background-color: rgb(51, 102, 255); color: white;")
        self.saveBtn.setObjectName("saveBtn")
        self.btnLayout.addWidget(self.saveBtn)
        
        self.defaultBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultBtn.sizePolicy().hasHeightForWidth())
        self.defaultBtn.setSizePolicy(sizePolicy)
        self.defaultBtn.setMinimumHeight(40)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.defaultBtn.setFont(font)
        self.defaultBtn.setStyleSheet("background-color: rgb(255, 153, 51); color: white;")
        self.defaultBtn.setObjectName("defaultBtn")
        self.btnLayout.addWidget(self.defaultBtn)
        
        self.cancelBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setMinimumHeight(40)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setStyleSheet("background-color: rgb(255, 51, 51); color: white;")
        self.cancelBtn.setObjectName("cancelBtn")
        self.btnLayout.addWidget(self.cancelBtn)
        
        self.quitBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitBtn.sizePolicy().hasHeightForWidth())
        self.quitBtn.setSizePolicy(sizePolicy)
        self.quitBtn.setMinimumHeight(40)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.quitBtn.setFont(font)
        self.quitBtn.setStyleSheet("background-color: rgb(128, 0, 128); color: white;")
        self.quitBtn.setObjectName("quitBtn")
        self.btnLayout.addWidget(self.quitBtn)
        
        self.verticalLayout.addLayout(self.btnLayout)
        
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.progressBar.setFont(font)
        self.progressBar.setMinimumHeight(35)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        
        self.statusLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        
        EzShareCPAP.setCentralWidget(self.centralwidget)
        self.actionStart = QtGui.QAction(parent=EzShareCPAP)
        self.actionStart.setObjectName("actionStart")
        self.actionSave_Settings = QtGui.QAction(parent=EzShareCPAP)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.actionRestore_Defaults = QtGui.QAction(parent=EzShareCPAP)
        self.actionRestore_Defaults.setObjectName("actionRestore_Defaults")
        self.actionCancel = QtGui.QAction(parent=EzShareCPAP)
        self.actionCancel.setObjectName("actionCancel")
        self.actionQuit = QtGui.QAction(parent=EzShareCPAP)
        self.actionQuit.setObjectName("actionQuit")
        self.actionBrowse = QtGui.QAction(parent=EzShareCPAP)
        self.actionBrowse.setObjectName("actionBrowse")

        self.retranslateUi(EzShareCPAP)
        QtCore.QMetaObject.connectSlotsByName(EzShareCPAP)

    def retranslateUi(self, EzShareCPAP):
        _translate = QtCore.QCoreApplication.translate
        EzShareCPAP.setWindowTitle(_translate("EzShareCPAP", "EzShareCPAP"))
        self.pathLabel.setText(_translate("EzShareCPAP", "Path:"))
        self.pathBrowseBtn.setText(_translate("EzShareCPAP", "Browse"))
        self.urlLabel.setText(_translate("EzShareCPAP", "URL:"))
        self.ssidLabel.setText(_translate("EzShareCPAP", "WiFi SSID:"))
        self.pskLabel.setText(_translate("EzShareCPAP", "WiFi PSK:"))
        self.importOscarCheckbox.setText(_translate("EzShareCPAP", "Import with OSCAR after completion"))
        self.quitCheckbox.setText(_translate("EzShareCPAP", "Quit after completion"))
        self.startBtn.setText(_translate("EzShareCPAP", "Start"))
        self.saveBtn.setText(_translate("EzShareCPAP", "Save Settings"))
        self.defaultBtn.setText(_translate("EzShareCPAP", "Restore Defaults"))
        self.cancelBtn.setText(_translate("EzShareCPAP", "Cancel"))
        self.quitBtn.setText(_translate("EzShareCPAP", "Quit"))
        self.statusLabel.setText(_translate("EzShareCPAP", "Ready."))
