from PySide6 import QtCore, QtGui, QtWidgets

class Ui_ezShareCPAP(object):
    def setupUi(self, ezShareCPAP):
        ezShareCPAP.setObjectName("ezShareCPAP")
        ezShareCPAP.resize(634, 387)
        self.centralwidget = QtWidgets.QWidget(ezShareCPAP)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSpacing(10)  # Set uniform vertical spacing

        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setObjectName("pathLayout")
        self.pathLayout.setSpacing(10)  # Set uniform horizontal spacing
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.pathLabel.setFont(font)
        self.pathLabel.setObjectName("pathLabel")
        self.pathLayout.addWidget(self.pathLabel)
        
        self.pathField = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathField.sizePolicy().hasHeightForWidth())
        self.pathField.setSizePolicy(sizePolicy)
        self.pathField.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.pathField.setFont(font)
        self.pathField.setReadOnly(True)
        self.pathField.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pathField.setObjectName("pathField")
        self.pathLayout.addWidget(self.pathField)
        
        self.pathBrowseBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathBrowseBtn.sizePolicy().hasHeightForWidth())
        self.pathBrowseBtn.setSizePolicy(sizePolicy)
        self.pathBrowseBtn.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.pathBrowseBtn.setFont(font)
        self.pathBrowseBtn.setObjectName("pathBrowseBtn")
        self.pathLayout.addWidget(self.pathBrowseBtn, 0, QtCore.Qt.AlignCenter)
        self.verticalLayout.addLayout(self.pathLayout)
        
        self.urlLayout = QtWidgets.QHBoxLayout()
        self.urlLayout.setObjectName("urlLayout")
        self.urlLayout.setSpacing(10)  # Set uniform horizontal spacing
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.urlLabel.setFont(font)
        self.urlLabel.setObjectName("urlLabel")
        self.urlLayout.addWidget(self.urlLabel)
        self.urlEntry = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlEntry.sizePolicy().hasHeightForWidth())
        self.urlEntry.setSizePolicy(sizePolicy)
        self.urlEntry.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.urlEntry.setFont(font)
        self.urlEntry.setObjectName("urlEntry")
        self.urlLayout.addWidget(self.urlEntry)
        self.verticalLayout.addLayout(self.urlLayout)
        
        self.ssidLayout = QtWidgets.QHBoxLayout()
        self.ssidLayout.setObjectName("ssidLayout")
        self.ssidLayout.setSpacing(10)  # Set uniform horizontal spacing
        self.ssidLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.ssidLabel.setFont(font)
        self.ssidLabel.setObjectName("ssidLabel")
        self.ssidLayout.addWidget(self.ssidLabel)
        self.ssidEntry = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ssidEntry.sizePolicy().hasHeightForWidth())
        self.ssidEntry.setSizePolicy(sizePolicy)
        self.ssidEntry.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.ssidEntry.setFont(font)
        self.ssidEntry.setObjectName("ssidEntry")
        self.ssidLayout.addWidget(self.ssidEntry)
        
        self.ezShareConfigBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ezShareConfigBtn.sizePolicy().hasHeightForWidth())
        self.ezShareConfigBtn.setSizePolicy(sizePolicy)
        self.ezShareConfigBtn.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.ezShareConfigBtn.setFont(font)
        self.ezShareConfigBtn.setObjectName("ezShareConfigBtn")
        self.ssidLayout.addWidget(self.ezShareConfigBtn, 0, QtCore.Qt.AlignCenter)
        self.verticalLayout.addLayout(self.ssidLayout)
        
        self.pskLayout = QtWidgets.QHBoxLayout()
        self.pskLayout.setObjectName("pskLayout")
        self.pskLayout.setSpacing(10)  # Set uniform horizontal spacing
        self.pskLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.pskLabel.setFont(font)
        self.pskLabel.setObjectName("pskLabel")
        self.pskLayout.addWidget(self.pskLabel)
        self.pskEntry = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pskEntry.sizePolicy().hasHeightForWidth())
        self.pskEntry.setSizePolicy(sizePolicy)
        self.pskEntry.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(14)
        self.pskEntry.setFont(font)
        self.pskEntry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pskEntry.setObjectName("pskEntry")
        self.pskLayout.addWidget(self.pskEntry)
        self.verticalLayout.addLayout(self.pskLayout)

        # Horizontal layout for group boxes
        self.groupBoxLayout = QtWidgets.QHBoxLayout()
        self.groupBoxLayout.setObjectName("groupBoxLayout")
        self.groupBoxLayout.setSpacing(10)  # Set uniform horizontal spacing

        # Group Box for "On Completion"
        self.onCompletionGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.onCompletionGroupBox.setObjectName("onCompletionGroupBox")
        self.onCompletionLayout = QtWidgets.QVBoxLayout(self.onCompletionGroupBox)
        self.onCompletionLayout.setObjectName("onCompletionLayout")
        self.onCompletionLayout.setSpacing(10)  # Set uniform vertical spacing

        self.importOscarCheckbox = QtWidgets.QCheckBox(self.onCompletionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importOscarCheckbox.sizePolicy().hasHeightForWidth())
        self.importOscarCheckbox.setSizePolicy(sizePolicy)
        self.importOscarCheckbox.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.importOscarCheckbox.setFont(font)
        self.importOscarCheckbox.setObjectName("importOscarCheckbox")
        self.importOscarCheckbox.setStyleSheet("background-color: transparent;")
        self.onCompletionLayout.addWidget(self.importOscarCheckbox)
        
        self.downloadOscarLink = QtWidgets.QLabel(self.onCompletionGroupBox)
        self.downloadOscarLink.setOpenExternalLinks(True)
        self.downloadOscarLink.setText('<a href="https://www.sleepfiles.com/OSCAR/">Download OSCAR</a>')
        self.downloadOscarLink.setAlignment(QtCore.Qt.AlignLeft)
        self.downloadOscarLink.setStyleSheet("background-color: transparent;")
        self.onCompletionLayout.addWidget(self.downloadOscarLink)

        self.quitCheckbox = QtWidgets.QCheckBox(self.onCompletionGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitCheckbox.sizePolicy().hasHeightForWidth())
        self.quitCheckbox.setSizePolicy(sizePolicy)
        self.quitCheckbox.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.quitCheckbox.setFont(font)
        self.quitCheckbox.setObjectName("quitCheckbox")
        self.quitCheckbox.setStyleSheet("background-color: transparent;")
        self.onCompletionLayout.addWidget(self.quitCheckbox)

        self.groupBoxLayout.addWidget(self.onCompletionGroupBox)

        # Group Box for "Settings"
        self.settingsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.settingsLayout = QtWidgets.QVBoxLayout(self.settingsGroupBox)
        self.settingsLayout.setObjectName("settingsLayout")
        self.settingsLayout.setSpacing(10)  # Set uniform vertical spacing

        self.saveBtn = QtWidgets.QPushButton(self.settingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBtn.sizePolicy().hasHeightForWidth())
        self.saveBtn.setSizePolicy(sizePolicy)
        self.saveBtn.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.settingsLayout.addWidget(self.saveBtn)
        
        self.defaultBtn = QtWidgets.QPushButton(self.settingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultBtn.sizePolicy().hasHeightForWidth())
        self.defaultBtn.setSizePolicy(sizePolicy)
        self.defaultBtn.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.defaultBtn.setFont(font)
        self.defaultBtn.setObjectName("defaultBtn")
        self.settingsLayout.addWidget(self.defaultBtn)

        self.groupBoxLayout.addWidget(self.settingsGroupBox)

        self.verticalLayout.addLayout(self.groupBoxLayout)

        self.btnLayout = QtWidgets.QHBoxLayout()
        self.btnLayout.setObjectName("btnLayout")
        
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startBtn.sizePolicy().hasHeightForWidth())
        self.startBtn.setSizePolicy(sizePolicy)
        self.startBtn.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.startBtn.setFont(font)
        self.startBtn.setObjectName("startBtn")
        self.btnLayout.addWidget(self.startBtn)
        
        self.cancelBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBtn.sizePolicy().hasHeightForWidth())
        self.cancelBtn.setSizePolicy(sizePolicy)
        self.cancelBtn.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.btnLayout.addWidget(self.cancelBtn)
        
        self.quitBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitBtn.sizePolicy().hasHeightForWidth())
        self.quitBtn.setSizePolicy(sizePolicy)
        self.quitBtn.setMinimumHeight(35)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(14)
        self.quitBtn.setFont(font)
        self.quitBtn.setObjectName("quitBtn")
        self.btnLayout.addWidget(self.quitBtn)
        
        self.verticalLayout.addLayout(self.btnLayout)
        
        ezShareCPAP.setCentralWidget(self.centralwidget)

        menubar = ezShareCPAP.menuBar()
        self.menuSettings = menubar.addMenu('Settings')
        self.menuTools = menubar.addMenu('Tools')

        self.actionLoad_Default = QtGui.QAction(ezShareCPAP)
        self.actionLoad_Default.setObjectName("actionLoad_Default")
        self.menuSettings.addAction(self.actionLoad_Default)

        self.actionChange_Path = QtGui.QAction(ezShareCPAP)
        self.actionChange_Path.setObjectName("actionChange_Path")
        self.menuSettings.addAction(self.actionChange_Path)

        self.actionSave_Settings = QtGui.QAction(ezShareCPAP)
        self.actionSave_Settings.setObjectName("actionSave_Settings")
        self.menuSettings.addAction(self.actionSave_Settings)

        self.actionEz_Share_Config = QtGui.QAction(ezShareCPAP)
        self.actionEz_Share_Config.setObjectName("actionEz_Share_Config")
        self.menuTools.addAction(self.actionEz_Share_Config)

        self.actionCheck_Access_Oscar = QtGui.QAction(ezShareCPAP)
        self.actionCheck_Access_Oscar.setObjectName("actionCheck_Access_Oscar")
        self.menuTools.addAction(self.actionCheck_Access_Oscar)

        self.actionQuit = QtGui.QAction(ezShareCPAP)
        self.actionQuit.setObjectName("actionQuit")
        self.menuTools.addAction(self.actionQuit)

        self.retranslateUi(ezShareCPAP)
        QtCore.QMetaObject.connectSlotsByName(ezShareCPAP)

    def retranslateUi(self, ezShareCPAP):
        _translate = QtCore.QCoreApplication.translate
        ezShareCPAP.setWindowTitle(_translate("ezShareCPAP", "ezShareCPAP"))
        self.pathLabel.setText(_translate("ezShareCPAP", "Path:"))
        self.pathBrowseBtn.setText(_translate("ezShareCPAP", "Browse"))
        self.urlLabel.setText(_translate("ezShareCPAP", "URL: "))
        self.ssidLabel.setText(_translate("ezShareCPAP", "WiFi SSID:"))
        self.pskLabel.setText(_translate("ezShareCPAP", "WiFi PSK: "))
        self.onCompletionGroupBox.setTitle(_translate("ezShareCPAP", "On Completion"))
        self.importOscarCheckbox.setText(_translate("ezShareCPAP", "Import with OSCAR after completion"))
        self.quitCheckbox.setText(_translate("ezShareCPAP", "Quit after completion"))
        self.settingsGroupBox.setTitle(_translate("ezShareCPAP", "Settings"))
        self.saveBtn.setText(_translate("ezShareCPAP", "Save"))
        self.defaultBtn.setText(_translate("ezShareCPAP", "Defaults"))
        self.startBtn.setText(_translate("ezShareCPAP", "Start"))
        self.cancelBtn.setText(_translate("ezShareCPAP", "Cancel"))
        self.quitBtn.setText(_translate("ezShareCPAP", "Quit"))
        self.ezShareConfigBtn.setText(_translate("ezShareCPAP", "ez Share Config"))
        self.actionLoad_Default.setText(_translate("ezShareCPAP", "Load Default"))
        self.actionChange_Path.setText(_translate("ezShareCPAP", "Change Path"))
        self.actionSave_Settings.setText(_translate("ezShareCPAP", "Save"))
        self.actionEz_Share_Config.setText(_translate("ezShareCPAP", "ez Share Config"))
        self.actionCheck_Access_Oscar.setText(_translate("ezShareCPAP", "Check Access To Oscar"))
        self.actionQuit.setText(_translate("ezShareCPAP", "Quit"))
