name: Build EzShareCPAP for macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        architecture: [x86_64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application
      run: |
        pyinstaller --onefile EzShareCPAP.py --distpath dist/${{ matrix.architecture }}
      shell: bash
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15  # or whatever minimum macOS version you support

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}
        path: dist/${{ matrix.architecture }}/EzShareCPAP*
