name: Build EzShareCPAP for macOS

on: [push, pull_request]

jobs:
  build:
    name: Build x86_64 package
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
        architecture: [x86_64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application with pyinstaller for x86_64
      run: |
        set -x  # Enable debug mode
        pyinstaller EzShareCPAP.spec --distpath dist/x86_64 --log-level=DEBUG
        mkdir -p dist/x86_64/EzShareCPAP-x86_64-3.9.app/Contents/MacOS
        mkdir -p dist/x86_64/EzShareCPAP-x86_64-3.9.app/Contents/Resources
        cp -R dist/x86_64/EzShareCPAP/* dist/x86_64/EzShareCPAP-x86_64-3.9.app/Contents/MacOS/
        cp icon.icns dist/x86_64/EzShareCPAP-x86_64-3.9.app/Contents/Resources/
        cp config.ini dist/x86_64/EzShareCPAP-x86_64-3.9.app/Contents/Resources/
        chmod +x dist/x86_64/EzShareCPAP-x86_64-3.9.app/Contents/MacOS/EzShareCPAP
        echo "Creating Info.plist"
        cat > dist/x86_64/EzShareCPAP-x86_64-3.9.app/Contents/Info.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleName</key>
            <string>EzShareCPAP</string>
            <key>CFBundleDisplayName</key>
            <string>EzShareCPAP</string>
            <key>CFBundleIdentifier</key>
            <string>com.ezsharecpap</string>
            <key>CFBundleVersion</key>
            <string>1.0.1</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.1</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleSignature</key>
            <string>????</string>
            <key>CFBundleExecutable</key>
            <string>EzShareCPAP</string>
            <key>CFBundleIconFile</key>
            <string>icon.icns</string>
            <key>NSAppTransportSecurity</key>
            <dict>
                <key>NSAllowsArbitraryLoads</key>
                <true/>
            </dict>
        </dict>
        </plist>
        EOF
        set +x  # Disable debug mode

    - name: Zip the application
      run: |
        cd dist/x86_64
        zip -r9 EzShareCPAP-x86_64-3.9.zip EzShareCPAP-x86_64-3.9.app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EzShareCPAP-x86_64-3.9
        path: dist/x86_64/EzShareCPAP-x86_64-3.9.zip

    - name: Show build log on failure
      if: failure()
      run: cat dist/x86_64/build.log || echo "No build log found"

    - name: Display build directory contents
      if: failure()
      run: ls -R dist/
