name: Build EzShareCPAP for macOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.12]  # Start with one Python version for simplicity
        architecture: [x86_64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application
      run: |
        pyinstaller --onefile EzShareCPAP.py --distpath dist/${{ matrix.architecture }} --log-level=DEBUG
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.15

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}
        path: dist/${{ matrix.architecture }}/EzShareCPAP*

    - name: Show build log on failure
      if: failure()
      run: cat dist/${{ matrix.architecture }}/build.log || echo "No build log found"

    - name: Display build directory contents
      if: failure()
      run: ls -R dist/
