name: Build EzShareCPAP for macOS

on: [push, pull_request]

jobs:
  build:
    name: Build packages
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
        architecture: [x86_64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application with pyinstaller for ${{ matrix.architecture }}
      run: |
        pyinstaller EzShareCPAP.spec --distpath dist/${{ matrix.architecture }} --log-level=DEBUG
        mkdir -p dist/${{ matrix.architecture }}/EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.app/Contents/MacOS
        mkdir -p dist/${{ matrix.architecture }}/EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.app/Contents/Resources
        cp dist/${{ matrix.architecture }}/EzShareCPAP dist/${{ matrix.architecture }}/EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.app/Contents/MacOS/EzShareCPAP
        cp icon.icns dist/${{ matrix.architecture }}/EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.app/Contents/Resources/icon.icns
        cp config.ini dist/${{ matrix.architecture }}/EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.app/Contents/Resources/config.ini
        chmod +x dist/${{ matrix.architecture }}/EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.app/Contents/MacOS/EzShareCPAP
        echo "Creating Info.plist"
        cat > dist/${{ matrix.architecture }}/EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.app/Contents/Info.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleName</key>
            <string>EzShareCPAP</string>
            <key>CFBundleDisplayName</key>
            <string>EzShareCPAP</string>
            <key>CFBundleIdentifier</key>
            <string>com.ezsharecpap</string>
            <key>CFBundleVersion</key>
            <string>1.0.1</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.1</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleSignature</key>
            <string>????</string>
            <key>CFBundleExecutable</key>
            <string>EzShareCPAP</string>
            <key>CFBundleIconFile</key>
            <string>icon.icns</string>
            <key>NSAppTransportSecurity</key>
            <dict>
                <key>NSAllowsArbitraryLoads</key>
                <true/>
            </dict>
        </dict>
        </plist>
        EOF
        cd dist/${{ matrix.architecture }}
        zip -r9 EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.zip EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}
        path: dist/${{ matrix.architecture }}/EzShareCPAP-${{ matrix.architecture }}-${{ matrix.python-version }}.zip

    - name: Show build log on failure
      if: failure()
      run: cat dist/${{ matrix.architecture }}/build.log || echo "No build log found"

    - name: Display build directory contents
      if: failure()
      run: ls -R dist/
